In [1]:
 
import os
 
%cd ../..
 
print(f"Current Working Directory: {os.getcwd()}")

/Users/aaronmcdonald/hm-fashion-recommender
Current Working Directory: /Users/aaronmcdonald/hm-fashion-recommender

/opt/anaconda3/envs/myenv/lib/python3.11/site-packages/IPython/core/magics/osm.py:417: UserWarning: This is now an optional IPython functionality, setting dhist requires you to install the `pickleshare` library.
  self.shell.db['dhist'] = compress_dhist(dhist)[-100:]

In [2]:
# dependicies and imports for data preparation, manipulation and visualization
import pandas as pd
import numpy as np
from datetime import timedelta
import matplotlib.pyplot as plt

# load all the raw data 
'''
customerData = pd.read_csv('/Users/aaronmcdonald/hm-fashion-recommender/data/raw/customers.csv')
articleData = pd.read_csv('/Users/aaronmcdonald/hm-fashion-recommender/data/raw/articles.csv')
transactionsData = pd.read_csv('/Users/aaronmcdonald/hm-fashion-recommender/data/raw/transactions_train .csv')
'''
 
customerData = pd.read_csv('data/raw/customers.csv')
articleData = pd.read_csv('data/raw/articles.csv')
transactionsData = pd.read_csv('data/raw/transactions_train.csv')

In [3]:
# merge all the data on to the transactions data
df = pd.merge(transactionsData, customerData, on='customer_id', how='left')
df = pd.merge(df, articleData, on='article_id', how='left')
df.head()

,t_dat,customer_id,article_id,price,sales_channel_id,FN,Active,club_member_status,fashion_news_frequency,age,...,department_name,index_code,index_name,index_group_no,index_group_name,section_no,section_name,garment_group_no,garment_group_name,detail_desc
0,2018-09-20,000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...,663713001,0.050831,2,NaN,NaN,ACTIVE,NONE,24.0,...,Expressive Lingerie,B,Lingeries/Tights,1,Ladieswear,61,Womens Lingerie,1017,"Under-, Nightwear","Lace push-up body with underwired, moulded, pa..."
1,2018-09-20,000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...,541518023,0.030492,2,NaN,NaN,ACTIVE,NONE,24.0,...,Casual Lingerie,B,Lingeries/Tights,1,Ladieswear,61,Womens Lingerie,1017,"Under-, Nightwear","Lace push-up bras with underwired, moulded, pa..."
2,2018-09-20,00007d2de826758b65a93dd24ce629ed66842531df6699...,505221004,0.015237,2,1.0,1.0,ACTIVE,Regularly,32.0,...,Tops Knitwear DS,D,Divided,2,Divided,58,Divided Selected,1003,Knitwear,Jumper in rib-knit cotton with hard-worn detai...
3,2018-09-20,00007d2de826758b65a93dd24ce629ed66842531df6699...,685687003,0.016932,2,1.0,1.0,ACTIVE,Regularly,32.0,...,Campaigns,A,Ladieswear,1,Ladieswear,15,Womens Everyday Collection,1023,Special Offers,V-neck knitted jumper with long sleeves and ri...
4,2018-09-20,00007d2de826758b65a93dd24ce629ed66842531df6699...,685687004,0.016932,2,1.0,1.0,ACTIVE,Regularly,32.0,...,Campaigns,A,Ladieswear,1,Ladieswear,15,Womens Everyday Collection,1023,Special Offers,V-neck knitted jumper with long sleeves and ri...

In [4]:
df.describe()

,article_id,price,sales_channel_id,FN,Active,age,product_code,product_type_no,graphical_appearance_no,colour_group_code,perceived_colour_value_id,perceived_colour_master_id,department_no,index_group_no,section_no,garment_group_no
count,3.178832e+07,3.178832e+07,3.178832e+07,13578487.0,13375856.0,3.164807e+07,3.178832e+07,3.178832e+07,3.178832e+07,3.178832e+07,3.178832e+07,3.178832e+07,3.178832e+07,3.178832e+07,3.178832e+07,3.178832e+07
mean,6.962272e+08,2.782927e-02,1.704028e+00,1.0,1.0,3.603827e+01,6.962272e+05,2.462434e+02,1.009727e+06,2.631858e+01,3.264336e+00,7.594182e+00,2.851993e+03,2.431111e+00,3.650995e+01,1.010718e+03
std,1.334480e+08,1.918113e-02,4.564786e-01,0.0,0.0,1.298003e+01,1.334480e+05,6.779323e+01,1.701311e+04,2.620701e+01,1.414001e+00,5.051449e+00,2.082204e+03,4.821826e+00,2.304772e+01,6.544575e+00
min,1.087750e+08,1.694915e-05,1.000000e+00,1.0,1.0,1.600000e+01,1.087750e+05,-1.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,1.201000e+03,1.000000e+00,2.000000e+00,1.001000e+03
25%,6.328030e+08,1.581356e-02,1.000000e+00,1.0,1.0,2.500000e+01,6.328030e+05,2.530000e+02,1.010011e+06,9.000000e+00,2.000000e+00,5.000000e+00,1.610000e+03,1.000000e+00,1.500000e+01,1.005000e+03
50%,7.145820e+08,2.540678e-02,2.000000e+00,1.0,1.0,3.100000e+01,7.145820e+05,2.650000e+02,1.010016e+06,1.000000e+01,4.000000e+00,5.000000e+00,1.717000e+03,1.000000e+00,4.700000e+01,1.010000e+03
75%,7.865240e+08,3.388136e-02,2.000000e+00,1.0,1.0,4.700000e+01,7.865240e+05,2.730000e+02,1.010016e+06,4.300000e+01,4.000000e+00,1.100000e+01,3.937000e+03,2.000000e+00,6.000000e+01,1.017000e+03
max,9.562170e+08,5.915254e-01,2.000000e+00,1.0,1.0,9.900000e+01,9.562170e+05,7.620000e+02,1.010029e+06,9.300000e+01,7.000000e+00,2.000000e+01,9.989000e+03,2.600000e+01,9.700000e+01,1.025000e+03

In [5]:
# view all columns and their null counts
df.isnull().sum()

t_dat                                  0
customer_id                            0
article_id                             0
price                                  0
sales_channel_id                       0
FN                              18209837
Active                          18412468
club_member_status                 62165
fashion_news_frequency            141713
age                               140258
postal_code                            0
product_code                           0
prod_name                              0
product_type_no                        0
product_type_name                      0
product_group_name                     0
graphical_appearance_no                0
graphical_appearance_name              0
colour_group_code                      0
colour_group_name                      0
perceived_colour_value_id              0
perceived_colour_value_name            0
perceived_colour_master_id             0
perceived_colour_master_name           0
department_no                          0
department_name                        0
index_code                             0
index_name                             0
index_group_no                         0
index_group_name                       0
section_no                             0
section_name                           0
garment_group_no                       0
garment_group_name                     0
detail_desc                       115027
dtype: int64

In [6]:
# drop the FN, Active, fashion_news_frequency columns
df = df.drop(columns=['FN', 'Active', 'fashion_news_frequency'])

# for the club_member_status column, drop the rows where the value is null or NaN or invalid
df = df[df['club_member_status'].notna()]

# for the age column, for rows with missing values, replace them with the median age
df['age'].fillna(df['age'].median(), inplace=True)

df.isnull().sum()

/var/folders/_0/dn5dccc95bqg3t95092yr1rr0000gn/T/ipykernel_93952/2176470804.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['age'].fillna(df['age'].median(), inplace=True)

t_dat                                0
customer_id                          0
article_id                           0
price                                0
sales_channel_id                     0
club_member_status                   0
age                                  0
postal_code                          0
product_code                         0
prod_name                            0
product_type_no                      0
product_type_name                    0
product_group_name                   0
graphical_appearance_no              0
graphical_appearance_name            0
colour_group_code                    0
colour_group_name                    0
perceived_colour_value_id            0
perceived_colour_value_name          0
perceived_colour_master_id           0
perceived_colour_master_name         0
department_no                        0
department_name                      0
index_code                           0
index_name                           0
index_group_no                       0
index_group_name                     0
section_no                           0
section_name                         0
garment_group_no                     0
garment_group_name                   0
detail_desc                     114771
dtype: int64

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 31726159 entries, 0 to 31788323
Data columns (total 32 columns):
 #   Column                        Dtype
---  ------                        -----
 0   t_dat                         object
 1   customer_id                   object
 2   article_id                    int64
 3   price                         float64
 4   sales_channel_id              int64
 5   club_member_status            object
 6   age                           float64
 7   postal_code                   object
 8   product_code                  int64
 9   prod_name                     object
 10  product_type_no               int64
 11  product_type_name             object
 12  product_group_name            object
 13  graphical_appearance_no       int64
 14  graphical_appearance_name     object
 15  colour_group_code             int64
 16  colour_group_name             object
 17  perceived_colour_value_id     int64
 18  perceived_colour_value_name   object
 19  perceived_colour_master_id    int64
 20  perceived_colour_master_name  object
 21  department_no                 int64
 22  department_name               object
 23  index_code                    object
 24  index_name                    object
 25  index_group_no                int64
 26  index_group_name              object
 27  section_no                    int64
 28  section_name                  object
 29  garment_group_no              int64
 30  garment_group_name            object
 31  detail_desc                   object
dtypes: float64(2), int64(12), object(18)
memory usage: 7.8+ GB

In [8]:
# now we need to filter the data to only include customers 
# aged 20-40 who have at least 40 transactions and to have only
#  transactions in the last 12 months, the latest t_dat is 2020-09-22 in the dataset


# convert t_date to datetime
df['t_dat'] = pd.to_datetime(df['t_dat'])
# filter the data to only include transactions in the last 12 months 
df = df[df['t_dat'] >= '2019-09-22']
print('The shape of the data after filtering for the most recent 12 months is ', df.shape)
# filter the data to only include customers aged 20-40
df = df[(df['age'] >= 20) & (df['age'] <=40)]
# filter the data to only include customers who have at least 40 transactions
# Get customer_ids with at least 40 transactions
eligible_customers = df['customer_id'].value_counts()
eligible_customers = eligible_customers[eligible_customers >= 40].index

# Filter df to only include those customers
df = df[df['customer_id'].isin(eligible_customers)]

print('The shape (aged 20-40 with at least 40 transactions in the most recent 12months within the dataset) is', df.shape)
# sort by datetime and customer_id, then group the rows by customer_id
df = df.sort_values(by=['customer_id', 't_dat'])
df.head(20)

The shape of the data after filtering for the most recent 12 months is  (14905795, 32)
The shape (aged 20-40 with at least 40 transactions in the most recent 12months within the dataset) is (3943069, 32)

,t_dat,customer_id,article_id,price,sales_channel_id,club_member_status,age,postal_code,product_code,prod_name,...,department_name,index_code,index_name,index_group_no,index_group_name,section_no,section_name,garment_group_no,garment_group_name,detail_desc
17074667,2019-09-28,0000f1c71aafe5963c3d195cf273f7bfd50bbf17761c91...,513512003,0.108458,2,ACTIVE,30.0,7c902dca60ee0bd0f9030eefd445d11146e8d24835738a...,513512,Peter softshell parka,...,Men Sport Tops,S,Sport,26,Sport,22,Men H&M Sport,1007,Outdoor,Parka in a sturdy weave with a drawstring hood...
17074668,2019-09-28,0000f1c71aafe5963c3d195cf273f7bfd50bbf17761c91...,535035001,0.094898,2,ACTIVE,30.0,7c902dca60ee0bd0f9030eefd445d11146e8d24835738a...,535035,Ultimate parka,...,Outdoor/Blazers DS,D,Divided,2,Divided,58,Divided Selected,1007,Outdoor,Padded parka with a pile-lined hood with a tab...
17074669,2019-09-28,0000f1c71aafe5963c3d195cf273f7bfd50bbf17761c91...,677930066,0.013542,2,ACTIVE,30.0,7c902dca60ee0bd0f9030eefd445d11146e8d24835738a...,677930,Queen Sweater,...,Basic 1,D,Divided,2,Divided,51,Divided Basics,1002,Jersey Basic,Top in lightweight sweatshirt fabric with ribb...
18758356,2019-11-08,0000f1c71aafe5963c3d195cf273f7bfd50bbf17761c91...,771528003,0.047712,2,ACTIVE,30.0,7c902dca60ee0bd0f9030eefd445d11146e8d24835738a...,771528,Jeff sweater,...,Knitwear,F,Menswear,3,Menswear,21,Contemporary Casual,1003,Knitwear,Long-sleeved jumper in a soft knit with ribbin...
18758357,2019-11-08,0000f1c71aafe5963c3d195cf273f7bfd50bbf17761c91...,793856005,0.047712,2,ACTIVE,30.0,7c902dca60ee0bd0f9030eefd445d11146e8d24835738a...,793856,Grape tee,...,Jersey,A,Ladieswear,1,Ladieswear,18,Womens Trend,1005,Jersey Fancy,T-shirt in jersey made from a silk and cotton ...
18758358,2019-11-08,0000f1c71aafe5963c3d195cf273f7bfd50bbf17761c91...,783925002,0.047712,2,ACTIVE,30.0,7c902dca60ee0bd0f9030eefd445d11146e8d24835738a...,783925,Puff sweater,...,Knitwear,A,Ladieswear,1,Ladieswear,6,Womens Casual,1003,Knitwear,"Jumper in a soft, fine knit containing some wo..."
18758359,2019-11-08,0000f1c71aafe5963c3d195cf273f7bfd50bbf17761c91...,784347001,0.015847,2,ACTIVE,30.0,7c902dca60ee0bd0f9030eefd445d11146e8d24835738a...,784347,Cap Rick Suede,...,Accessories,F,Menswear,3,Menswear,25,Men Accessories,1019,Accessories,Imitation suede cap with an adjustable tab and...
18758360,2019-11-08,0000f1c71aafe5963c3d195cf273f7bfd50bbf17761c91...,791152003,0.047712,2,ACTIVE,30.0,7c902dca60ee0bd0f9030eefd445d11146e8d24835738a...,791152,Daniel sweater,...,Knitwear,A,Ladieswear,1,Ladieswear,11,Womens Tailoring,1003,Knitwear,Jumper in a soft knit containing some wool wit...
19077503,2019-11-19,0000f1c71aafe5963c3d195cf273f7bfd50bbf17761c91...,803118001,0.033881,2,ACTIVE,30.0,7c902dca60ee0bd0f9030eefd445d11146e8d24835738a...,803118,Heart,...,Loungewear,A,Ladieswear,1,Ladieswear,62,"Womens Nightwear, Socks & Tigh",1017,"Under-, Nightwear","Short dress in a soft, fine knit with a ribbed..."
19077504,2019-11-19,0000f1c71aafe5963c3d195cf273f7bfd50bbf17761c91...,805772003,0.025407,2,ACTIVE,30.0,7c902dca60ee0bd0f9030eefd445d11146e8d24835738a...,805772,Mary Kate Mock Neck,...,Tops Knitwear,D,Divided,2,Divided,53,Divided Collection,1003,Knitwear,"Fitted jumper in a soft, airy, fine knit with ..."
19077505,2019-11-19,0000f1c71aafe5963c3d195cf273f7bfd50bbf17761c91...,678942032,0.016932,2,ACTIVE,30.0,7c902dca60ee0bd0f9030eefd445d11146e8d24835738a...,678942,Harrison (1),...,Loungewear,A,Ladieswear,1,Ladieswear,62,"Womens Nightwear, Socks & Tigh",1017,"Under-, Nightwear","Short-sleeved jumper in a soft, fine-knit visc..."
19077506,2019-11-19,0000f1c71aafe5963c3d195cf273f7bfd50bbf17761c91...,820601001,0.033881,2,ACTIVE,30.0,7c902dca60ee0bd0f9030eefd445d11146e8d24835738a...,820601,Dalila dress,...,Jersey fancy,A,Ladieswear,1,Ladieswear,15,Womens Everyday Collection,1005,Jersey Fancy,Short dress in jersey with a soft brushed fini...
19463621,2019-11-29,0000f1c71aafe5963c3d195cf273f7bfd50bbf17761c91...,828114001,0.027102,2,ACTIVE,30.0,7c902dca60ee0bd0f9030eefd445d11146e8d24835738a...,828114,Esmeralda,...,Knitwear,A,Ladieswear,1,Ladieswear,15,Womens Everyday Collection,1003,Knitwear,Jumper in a soft knit containing some wool wit...
19463622,2019-11-29,0000f1c71aafe5963c3d195cf273f7bfd50bbf17761c91...,803229002,0.020322,2,ACTIVE,30.0,7c902dca60ee0bd0f9030eefd445d11146e8d24835738a...,803229,Darla Mesh Tee,...,Ladies Sport Bras,S,Sport,26,Sport,5,Ladies H&M Sport,1005,Jersey Fancy,Short sports top in fast-drying functional fab...
19463623,2019-11-29,0000f1c71aafe5963c3d195cf273f7bfd50bbf17761c91...,754423002,0.033881,2,ACTIVE,30.0,7c902dca60ee0bd0f9030eefd445d11146e8d24835738a...,754423,SADE strap top,...,Ladies Sport Bras,S,Sport,26,Sport,5,Ladies H&M Sport,1005,Jersey Fancy,Fitted sports vest top in fast-drying function...
21088707,2020-01-09,0000f1c71aafe5963c3d195cf273f7bfd50bbf17761c91...,799979001,0.022017,2,ACTIVE,30.0,7c902dca60ee0bd0f9030eefd445d11146e8d24835738a...,799979,CONSCIOUS Tee,...,Men Sport Woven,S,Sport,26,Sport,22,Men H&M Sport,1005,Jersey Fancy,"Short-sleeved top in fast-drying, breathable f..."
21088708,2020-01-09,0000f1c71aafe5963c3d195cf273f7bfd50bbf17761c91...,791587001,0.025407,2,ACTIVE,30.0,7c902dca60ee0bd0f9030eefd445d11146e8d24835738a...,791587,Speedy tee (C),...,Ladies Sport Bras,S,Sport,26,Sport,5,Ladies H&M Sport,1005,Jersey Fancy,Straight-cut sports top in fast-drying mesh wi...
22466522,2020-02-18,0000f1c71aafe5963c3d195cf273f7bfd50bbf17761c91...,809238001,0.038119,2,ACTIVE,30.0,7c902dca60ee0bd0f9030eefd445d11146e8d24835738a...,809238,Atomic Wrap Sweater,...,Tops Knitwear,D,Divided,2,Divided,53,Divided Collection,1003,Knitwear,Cardigan in a soft knit with a wrapover front ...
22466523,2020-02-18,0000f1c71aafe5963c3d195cf273f7bfd50bbf17761c91...,879925001,0.030492,2,ACTIVE,30.0,7c902dca60ee0bd0f9030eefd445d11146e8d24835738a...,879925,Megane Flared Leggings,...,Trousers,D,Divided,2,Divided,53,Divided Collection,1009,Trousers,"Flared, ankle-length leggings in velour with a..."
22466524,2020-02-18,0000f1c71aafe5963c3d195cf273f7bfd50bbf17761c91...,562245102,0.030492,2,ACTIVE,30.0,7c902dca60ee0bd0f9030eefd445d11146e8d24835738a...,562245,Luna skinny RW,...,Trouser,A,Ladieswear,1,Ladieswear,15,Womens Everyday Collection,1009,Trousers,"5-pocket jeans in washed, superstretch denim w..."

In [9]:
# create new csv file for the filtered data
#df.to_csv('/Users/aaronmcdonald/hm-fashion-recommender/data/processed/transactions_train_filtered.csv', index=False)

df.to_csv('data/processed/transactions_train_filtered.csv', index=False)

In [10]:
# load transactions
#transactions = pd.read_csv(r'C:\Users\arlen\OneDrive\Documents\GitHub\hm-fashion-recommender\data\processed\transactions_train_filtered.csv')
transactions = pd.read_csv('data/processed/transactions_train_filtered.csv')


#sort transactions by id and then date so it is in chronological order
transactions['t_dat'] = pd.to_datetime(transactions['t_dat'])
transactions = transactions.sort_values(['customer_id', 't_dat'])

In [11]:
# split into train/test by date
max_date = transactions['t_dat'].max() #latest transaction
test_cutoff = max_date - timedelta(days=7)  #last 7 days for testing, before are for training

customer_groups = transactions.groupby('customer_id') #group by id to do transasctions per customer

# create train/test sequences for each customer
customer_sequences_train = []
customer_sequences_test = []
customer_ids_train = []
customer_ids_test = []

for customer_id, group in customer_groups:
    group = group.sort_values('t_dat')
    train = group[group['t_dat'] <= test_cutoff]['article_id'].tolist()
    test = group[group['t_dat'] > test_cutoff]['article_id'].tolist()
    if len(train) >= 7: #keeps only customers with at least 7 training transactions
        customer_sequences_train.append(train)
        customer_ids_train.append(customer_id)
        if len(test) > 0:
            customer_sequences_test.append(test)
            customer_ids_test.append(customer_id)

In [12]:
# generate sliding window sequences
window_size = 7
target_size = 7
X = [] #input sequences
Y = [] #output sequences
for seq in customer_sequences_train:
    if len(seq) < window_size + target_size: #skips if sequence is too short
        continue
    for i in range(len(seq) - window_size - target_size + 1): #creates sliding windows for each possible position with window size as input and target size as output
        X.append(seq[i:i+window_size])
        Y.append(seq[i+window_size:i+window_size+target_size])

In [13]:
# label encode the article IDs
all_articles = sorted(set([a for seq in X+Y for a in seq])) #sorts all unique IDs
article_to_idx = {article: idx for idx, article in enumerate(all_articles)} #maps each article to a unique integer
idx_to_article = {idx: article for article, idx in article_to_idx.items()} #reverse mapping from integer to article ID
X_encoded = [[article_to_idx[a] for a in seq] for seq in X] #input sequences encoded as integers
Y_encoded = [[article_to_idx[a] for a in seq] for seq in Y] #output sequences encoded as integers

In [14]:
#Checking the results
print(f"Number of customers in train: {len(customer_sequences_train)}")
print(f"First train sequence: {customer_sequences_train[0]}")
print(f"First encoded X: {X_encoded[0]}")
print(f"First encoded Y: {Y_encoded[0]}")

Number of customers in train: 56590
First train sequence: [513512003, 535035001, 677930066, 771528003, 793856005, 783925002, 784347001, 791152003, 678942032, 820601001, 803118001, 805772003, 828114001, 803229002, 754423002, 799979001, 791587001, 809238001, 879925001, 562245102, 857924002, 590928022, 599580049, 841260013, 717490065, 749699019, 852521001, 749699002, 841383002, 749699001, 889714001, 832732003, 864716001, 832482001, 926847002, 902325002, 870345002, 835851001, 685814048, 895418003, 917434002, 875469002, 946748003, 909924004, 917434002, 722803001]
First encoded X: [2667, 3341, 13344, 31210, 35665, 33682, 33796]
First encoded Y: [35105, 13485, 42360, 37793, 38499, 44059, 37826]

In [15]:

# prepare test data, use same sliding logic

X_test = [] 
Y_test = []
for seq in customer_sequences_test:  
    if len(seq) < window_size + target_size:
        continue
    for i in range(len(seq) - window_size - target_size + 1):
        X_test.append(seq[i:i+window_size])
        Y_test.append(seq[i+window_size:i+window_size+target_size])

# encode test sequences using same mapping from training
X_test_encoded = [[article_to_idx.get(a, 0) for a in seq] for seq in X_test]  
Y_test_encoded = [[article_to_idx.get(a, 0) for a in seq] for seq in Y_test]
 
import torch

# convert lists to tensors
X_train_tensor = torch.tensor(X_encoded, dtype=torch.long)
Y_train_tensor = torch.tensor(Y_encoded, dtype=torch.long)
X_test_tensor = torch.tensor(X_test_encoded, dtype=torch.long)
Y_test_tensor = torch.tensor(Y_test_encoded, dtype=torch.long)
 
# save final tensor and mapping, to be later fed into model
torch.save({
    'X_train': X_train_tensor,
    'Y_train': Y_train_tensor,
    'X_test': X_test_tensor,
    'Y_test': Y_test_tensor,
    'article_to_idx': article_to_idx,
    'idx_to_article': idx_to_article
}, 'data/processed/final_lstm_data.pth')  

print("Data preparation complete. Saved to 'data/processed/final_lstm_data.pth'")

Data preparation complete. Saved to 'data/processed/final_lstm_data.pth'