In [1]:
# import dependencies 
import pandas as pd

In [2]:
# read in the all the necessary data
customersData = pd.read_csv('/Users/aaronmcdonald/hm-fashion-recommender/data/raw/customers.csv')

In [3]:
customersData.shape

(1371980, 7)

In [4]:
customersData.columns

Index(['customer_id', 'FN', 'Active', 'club_member_status',
       'fashion_news_frequency', 'age', 'postal_code'],
      dtype='object')

In [5]:
customersData.describe()

             FN    Active           age
count  476930.0  464404.0  1.356119e+06
mean        1.0       1.0  3.638696e+01
std         0.0       0.0  1.431363e+01
min         1.0       1.0  1.600000e+01
25%         1.0       1.0  2.400000e+01
50%         1.0       1.0  3.200000e+01
75%         1.0       1.0  4.900000e+01
max         1.0       1.0  9.900000e+01

In [6]:
customersData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1371980 entries, 0 to 1371979
Data columns (total 7 columns):
 #   Column                  Non-Null Count    Dtype
---  ------                  --------------    -----
 0   customer_id             1371980 non-null  object
 1   FN                      476930 non-null   float64
 2   Active                  464404 non-null   float64
 3   club_member_status      1365918 non-null  object
 4   fashion_news_frequency  1355969 non-null  object
 5   age                     1356119 non-null  float64
 6   postal_code             1371980 non-null  object
dtypes: float64(3), object(4)
memory usage: 73.3+ MB

In [7]:
customersData.head(10)

,customer_id,FN,Active,club_member_status,fashion_news_frequency,age,postal_code
0,00000dbacae5abe5e23885899a1fa44253a17956c6d1c3...,NaN,NaN,ACTIVE,NONE,49.0,52043ee2162cf5aa7ee79974281641c6f11a68d276429a...
1,0000423b00ade91418cceaf3b26c6af3dd342b51fd051e...,NaN,NaN,ACTIVE,NONE,25.0,2973abc54daa8a5f8ccfe9362140c63247c5eee03f1d93...
2,000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...,NaN,NaN,ACTIVE,NONE,24.0,64f17e6a330a85798e4998f62d0930d14db8db1c054af6...
3,00005ca1c9ed5f5146b52ac8639a40ca9d57aeff4d1bd2...,NaN,NaN,ACTIVE,NONE,54.0,5d36574f52495e81f019b680c843c443bd343d5ca5b1c2...
4,00006413d8573cd20ed7128e53b7b13819fe5cfc2d801f...,1.0,1.0,ACTIVE,Regularly,52.0,25fa5ddee9aac01b35208d01736e57942317d756b32ddd...
5,000064249685c11552da43ef22a5030f35a147f723d5b0...,NaN,NaN,NaN,NaN,NaN,2c29ae653a9282cce4151bd87643c907644e09541abc28...
6,0000757967448a6cb83efb3ea7a3fb9d418ac7adf2379d...,NaN,NaN,ACTIVE,NONE,20.0,fe7b8e2b3fafb89ca90db17ffeeae0fd29b795d803f749...
7,00007d2de826758b65a93dd24ce629ed66842531df6699...,1.0,1.0,ACTIVE,Regularly,32.0,8d6f45050876d059c830a0fe63f1a4c022de279bb68ce3...
8,00007e8d4e54114b5b2a9b51586325a8d0fa74ea23ef77...,NaN,NaN,ACTIVE,NONE,20.0,2c29ae653a9282cce4151bd87643c907644e09541abc28...
9,00008469a21b50b3d147c97135e25b4201a8c58997f787...,NaN,NaN,ACTIVE,NONE,20.0,2c29ae653a9282cce4151bd87643c907644e09541abc28...

In [8]:
# drop the 'Active' and 'FN' columns 
customersData = customersData.drop(['Active', 'FN'], axis = 1)
# drop the rows with NaN values in the 'club_member_status' column
customersData = customersData.dropna(subset=['club_member_status'])

customersData.head()

,customer_id,club_member_status,fashion_news_frequency,age,postal_code
0,00000dbacae5abe5e23885899a1fa44253a17956c6d1c3...,ACTIVE,NONE,49.0,52043ee2162cf5aa7ee79974281641c6f11a68d276429a...
1,0000423b00ade91418cceaf3b26c6af3dd342b51fd051e...,ACTIVE,NONE,25.0,2973abc54daa8a5f8ccfe9362140c63247c5eee03f1d93...
2,000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...,ACTIVE,NONE,24.0,64f17e6a330a85798e4998f62d0930d14db8db1c054af6...
3,00005ca1c9ed5f5146b52ac8639a40ca9d57aeff4d1bd2...,ACTIVE,NONE,54.0,5d36574f52495e81f019b680c843c443bd343d5ca5b1c2...
4,00006413d8573cd20ed7128e53b7b13819fe5cfc2d801f...,ACTIVE,Regularly,52.0,25fa5ddee9aac01b35208d01736e57942317d756b32ddd...

In [9]:
# drop the rest of rows with null values in them
customersData = customersData.dropna(subset=['fashion_news_frequency'])
customersData = customersData.dropna(subset=['age'])

# validate that there are no more null values in the data 
customersData.isnull().sum()

customer_id               0
club_member_status        0
fashion_news_frequency    0
age                       0
postal_code               0
dtype: int64

In [10]:
customersData.shape

(1338568, 5)

In [11]:

# count number of customers within desired age range 
((customersData['age'] > 20) & (customersData['age'] < 40)).sum()

np.int64(698781)

In [12]:
# eliminate rows of data of people who are not between ages 20 and 40 years old
customersData = customersData[(customersData['age'] > 19) & (customersData['age'] < 41)]
# display the amount of customers for each age from 20 to 40 years old
customersData['age'].value_counts()

age
21.0    66807
24.0    55518
20.0    54555
25.0    54338
23.0    54321
26.0    53043
22.0    51342
27.0    48574
28.0    43753
29.0    40185
30.0    38796
31.0    35910
32.0    27985
33.0    24477
34.0    21473
35.0    19602
36.0    17182
40.0    15897
37.0    15783
38.0    15008
39.0    14684
Name: count, dtype: int64

In [13]:
demographic = customersData['customer_id'].nunique()

# show the number of individuals within are target demographic that we are studying 
print('There are', demographic, 'individuals within the H&M dataset that are aged 20-40 years old.')

There are 769233 individuals within the H&M dataset that are aged 20-40 years old.

In [14]:
transactionsData = pd.read_csv('/Users/aaronmcdonald/hm-fashion-recommender/data/raw/transactions_train .csv')
transactionsData.head(15)

,t_dat,customer_id,article_id,price,sales_channel_id
0,2018-09-20,000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...,663713001,0.050831,2
1,2018-09-20,000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...,541518023,0.030492,2
2,2018-09-20,00007d2de826758b65a93dd24ce629ed66842531df6699...,505221004,0.015237,2
3,2018-09-20,00007d2de826758b65a93dd24ce629ed66842531df6699...,685687003,0.016932,2
4,2018-09-20,00007d2de826758b65a93dd24ce629ed66842531df6699...,685687004,0.016932,2
5,2018-09-20,00007d2de826758b65a93dd24ce629ed66842531df6699...,685687001,0.016932,2
6,2018-09-20,00007d2de826758b65a93dd24ce629ed66842531df6699...,505221001,0.020322,2
7,2018-09-20,00083cda041544b2fbb0e0d2905ad17da7cf1007526fb4...,688873012,0.030492,1
8,2018-09-20,00083cda041544b2fbb0e0d2905ad17da7cf1007526fb4...,501323011,0.053373,1
9,2018-09-20,00083cda041544b2fbb0e0d2905ad17da7cf1007526fb4...,598859003,0.045746,2
10,2018-09-20,00083cda041544b2fbb0e0d2905ad17da7cf1007526fb4...,688873020,0.030492,1
11,2018-09-20,00083cda041544b2fbb0e0d2905ad17da7cf1007526fb4...,688873011,0.030492,1
12,2018-09-20,0008968c0d451dbc5a9968da03196fe20051965edde741...,531310002,0.022525,2
13,2018-09-20,0008968c0d451dbc5a9968da03196fe20051965edde741...,529841001,0.020322,2
14,2018-09-20,000aa7f0dc06cd7174389e76c9e132a67860c5f65f9706...,501820043,0.016932,2

In [15]:
frequencyOf_customers = transactionsData['customer_id'].value_counts()

# Get the customer IDs who have made 20 transactionseers >= 10
customerIds = frequencyOf_customers[frequencyOf_customers == 20].index

In [16]:
# filtered the data for only transactions associated with customers who are aged have greater than 9 transactions recorded in the dataset
filtered_transactions = transactionsData[transactionsData['customer_id'].isin(customerIds)]
# count every unique id in the customer_id column of new dataframe
customers = filtered_transactions['customer_id'].nunique()
print('There are', customers, 'that have a recorded transaction history equal to 20 total transactions')

There are 16084 that have a recorded transaction history equal to 20 total transactions

In [17]:
# filtered the data for only transactions associated with customers who are aged 20-40
filtered_transactions = filtered_transactions[filtered_transactions['customer_id'].isin(customersData['customer_id'])]

obs = filtered_transactions['customer_id'].nunique()
print('There are', obs, 'H&M customers aged 20-40 who have a recorded transaction history equal to 20 total transactions')
print('In our target population there are', filtered_transactions['customer_id'].count(), 'different transactions among H&M customers within our desired demographic for the study.')

There are 9482 H&M customers aged 20-40 who have a recorded transaction history equal to 20 total transactions
In our target population there are 189640 different transactions among H&M customers within our desired demographic for the study.

In [18]:
final_transactions = filtered_transactions.sort_values('customer_id')
print(final_transactions.shape)
final_transactions.head(15)

(189640, 5)

,t_dat,customer_id,article_id,price,sales_channel_id
29714160,2020-07-31,000346516dd355b40badca0c0f5f37a318ddae31f0e0f7...,816423002,0.025407,1
3170499,2018-11-28,000346516dd355b40badca0c0f5f37a318ddae31f0e0f7...,534210011,0.015237,2
3417797,2018-12-06,000346516dd355b40badca0c0f5f37a318ddae31f0e0f7...,557248003,0.027102,2
3170500,2018-11-28,000346516dd355b40badca0c0f5f37a318ddae31f0e0f7...,666084001,0.022017,2
6133786,2019-02-13,000346516dd355b40badca0c0f5f37a318ddae31f0e0f7...,507909001,0.025407,1
11032976,2019-05-30,000346516dd355b40badca0c0f5f37a318ddae31f0e0f7...,642437010,0.033881,1
11032977,2019-05-30,000346516dd355b40badca0c0f5f37a318ddae31f0e0f7...,745232001,0.025407,1
11032978,2019-05-30,000346516dd355b40badca0c0f5f37a318ddae31f0e0f7...,685823003,0.033881,1
19463625,2019-11-29,000346516dd355b40badca0c0f5f37a318ddae31f0e0f7...,827636001,0.033881,1
19463626,2019-11-29,000346516dd355b40badca0c0f5f37a318ddae31f0e0f7...,809672001,0.027102,2
29714159,2020-07-31,000346516dd355b40badca0c0f5f37a318ddae31f0e0f7...,854193002,0.016932,1
29714161,2020-07-31,000346516dd355b40badca0c0f5f37a318ddae31f0e0f7...,825811006,0.018627,1
27731532,2020-06-22,000346516dd355b40badca0c0f5f37a318ddae31f0e0f7...,816588001,0.022017,2
11032979,2019-05-30,000346516dd355b40badca0c0f5f37a318ddae31f0e0f7...,485176004,0.022017,1
15568283,2019-08-17,000346516dd355b40badca0c0f5f37a318ddae31f0e0f7...,456163030,0.022017,2

In [19]:
final_customersData = customersData[customersData['customer_id'].isin(final_transactions['customer_id'])]
print(final_customersData.shape)
customersData.head()

(9482, 5)

,customer_id,club_member_status,fashion_news_frequency,age,postal_code
1,0000423b00ade91418cceaf3b26c6af3dd342b51fd051e...,ACTIVE,NONE,25.0,2973abc54daa8a5f8ccfe9362140c63247c5eee03f1d93...
2,000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...,ACTIVE,NONE,24.0,64f17e6a330a85798e4998f62d0930d14db8db1c054af6...
6,0000757967448a6cb83efb3ea7a3fb9d418ac7adf2379d...,ACTIVE,NONE,20.0,fe7b8e2b3fafb89ca90db17ffeeae0fd29b795d803f749...
7,00007d2de826758b65a93dd24ce629ed66842531df6699...,ACTIVE,Regularly,32.0,8d6f45050876d059c830a0fe63f1a4c022de279bb68ce3...
8,00007e8d4e54114b5b2a9b51586325a8d0fa74ea23ef77...,ACTIVE,NONE,20.0,2c29ae653a9282cce4151bd87643c907644e09541abc28...

In [20]:
articlesData = pd.read_csv('/Users/aaronmcdonald/hm-fashion-recommender/data/raw/articles.csv')

final_articlesData = articlesData[articlesData['article_id'].isin(final_transactions['article_id'])]
# Make sure all columns are shown in .info()
pd.set_option('display.max_columns', None)
final_articlesData.info()

<class 'pandas.core.frame.DataFrame'>
Index: 40337 entries, 0 to 105538
Data columns (total 25 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   article_id                    40337 non-null  int64
 1   product_code                  40337 non-null  int64
 2   prod_name                     40337 non-null  object
 3   product_type_no               40337 non-null  int64
 4   product_type_name             40337 non-null  object
 5   product_group_name            40337 non-null  object
 6   graphical_appearance_no       40337 non-null  int64
 7   graphical_appearance_name     40337 non-null  object
 8   colour_group_code             40337 non-null  int64
 9   colour_group_name             40337 non-null  object
 10  perceived_colour_value_id     40337 non-null  int64
 11  perceived_colour_value_name   40337 non-null  object
 12  perceived_colour_master_id    40337 non-null  int64
 13  perceived_colour_master_name  40337 non-null  object
 14  department_no                 40337 non-null  int64
 15  department_name               40337 non-null  object
 16  index_code                    40337 non-null  object
 17  index_name                    40337 non-null  object
 18  index_group_no                40337 non-null  int64
 19  index_group_name              40337 non-null  object
 20  section_no                    40337 non-null  int64
 21  section_name                  40337 non-null  object
 22  garment_group_no              40337 non-null  int64
 23  garment_group_name            40337 non-null  object
 24  detail_desc                   40182 non-null  object
dtypes: int64(11), object(14)
memory usage: 8.0+ MB

In [21]:
final_articlesData.head()

,article_id,product_code,prod_name,product_type_no,product_type_name,product_group_name,graphical_appearance_no,graphical_appearance_name,colour_group_code,colour_group_name,perceived_colour_value_id,perceived_colour_value_name,perceived_colour_master_id,perceived_colour_master_name,department_no,department_name,index_code,index_name,index_group_no,index_group_name,section_no,section_name,garment_group_no,garment_group_name,detail_desc
0,108775015,108775,Strap top,253,Vest top,Garment Upper body,1010016,Solid,9,Black,4,Dark,5,Black,1676,Jersey Basic,A,Ladieswear,1,Ladieswear,16,Womens Everyday Basics,1002,Jersey Basic,Jersey top with narrow shoulder straps.
1,108775044,108775,Strap top,253,Vest top,Garment Upper body,1010016,Solid,10,White,3,Light,9,White,1676,Jersey Basic,A,Ladieswear,1,Ladieswear,16,Womens Everyday Basics,1002,Jersey Basic,Jersey top with narrow shoulder straps.
3,110065001,110065,OP T-shirt (Idro),306,Bra,Underwear,1010016,Solid,9,Black,4,Dark,5,Black,1339,Clean Lingerie,B,Lingeries/Tights,1,Ladieswear,61,Womens Lingerie,1017,"Under-, Nightwear","Microfibre T-shirt bra with underwired, moulde..."
4,110065002,110065,OP T-shirt (Idro),306,Bra,Underwear,1010016,Solid,10,White,3,Light,9,White,1339,Clean Lingerie,B,Lingeries/Tights,1,Ladieswear,61,Womens Lingerie,1017,"Under-, Nightwear","Microfibre T-shirt bra with underwired, moulde..."
5,110065011,110065,OP T-shirt (Idro),306,Bra,Underwear,1010016,Solid,12,Light Beige,1,Dusty Light,11,Beige,1339,Clean Lingerie,B,Lingeries/Tights,1,Ladieswear,61,Womens Lingerie,1017,"Under-, Nightwear","Microfibre T-shirt bra with underwired, moulde..."